### ISSUE TITLE
Suppress svg.path element if no children

### ISSUE THREAD

**Issue by RobWunderlich** [excubo-ag/Blazor.TreeViews#42]
I need to control the color of the svg collapse indicator using css as I switch between different themes in my app. I can target the color using css like:
```
svg path {
        stroke: green;
    }
```
 This works, but a side effect is the indicator is visible for nodes with no children.  The no-children \<path\> is generated with `stroke="transparent"` but is overridden by the css stroke.

A proposed solution is to not generate the \<path\> element if there are no children. Change to `ListItem.razor`:
```
@if (HasChildren) {
    <path d="M 4 2 l 7 6 l -7 6" class="@(TreeView.Disabled ? "tree-view-disabled" : "")" stroke="@(TreeView.Disabled ? "gray" : "black")" fill="transparent" stroke-width="2" />
}
```
https://github.com/RobWunderlich/Blazor.TreeViews/commit/6cadd87dec6e4547de7e9fb76a0fc7ef3f972c47

I also added `class="tree-view-disabled"` for disabled nodes to allow css targeting.

**Comment by stefanloerwald** [comment]
Hi @RobWunderlich,

Thanks for uncovering this. Wouldn't it be easier if we also defined a `treeview` css class that controls the stroke & fill? I didn't try this out, but something like the following should work:

```
@{ 
   var classes = string.Join(";",
      "excubo-blazor-treeview",
      (TreeView.Disabled ? "excubo-blazor-treeview-disabled" : ""),
      (HasChildren ? "" : "excubo-blazor-treeview-nochildren")
   );
}
<path d="M 4 2 l 7 6 l -7 6" class="@classes" />
```

Default CSS would then be something like

```css
svg path .excubo-blazor-treeview {
   stroke: black;
   fill: transparent;
   stroke-width: 2;
}
svg path .excubo-blazor-treeview-disabled {
   stroke: gray;
}
svg path .excubo-blazor-treeview-nochildren {
   stroke: transparent;
}
```

Would that enable you to customize the path element correctly?

Thanks,
Stefan
